### ISSUE TITLE
read() throws error when transfer size is 1 MB

### ISSUE THREAD

**Issue by farzad64** [jeremytrimble/ezdma#2]
Hi Jeremy,

I am using ezdma with Xilinx AXI DMA. When I try to initiate a 1 MB read transfer, ezdma throws this error:
ezdma: loop_rx: dmaengine_prep_slave_sg() failed

I traced the error back to xilinx_dma_alloc_tx_segment() which is called by xilinx_dma_prep_slave_sg(). This function returns NULL (free_seg_list is empty?).  I also tried to find the maximum possible size. It turns out to be 1 MB minus 8192 bytes.

Any idea on this? Is it a Xilinx driver issue or ezdma one?
Does it happen to have a relation with the maximum number of descriptors "XILINX_DMA_NUM_DESCS" defined in the Xilinx driver?

Best,
Farzad

**Comment by jeremytrimble** [comment]
Farzad,

I'm guessing this is an issue with the xilinx driver (I'm currently fighting with several issues in that driver, xilinx_dma.c, commit 5dab41c3eb8acd273f26f36b5598cbaa0703f2c0).

If you're using a recent xilinx_dma.c, one of the things they changed since I originally wrote ezdma is how the "segments" are allocated (they now use a fixed-size pool which is allocated up-front).  You can increase the size of the pool by changing the #define XILINX_DMA_NUM_DESCS to something larger.  I suspect increasing this should help you do larger transfers, although the exact maximum will depend somewhat on how fragmented your read buffer is in physical address terms.

For the record, I liked the old approach (using a dma_pool for the buffer descriptors (aka "segments")) much better, as I routinely have cases where I need lots of descriptors, and the new approach is inflexible and wastes memory.

**Comment by farzad64** [comment]
Thanks for your response. I'll give it a try.

**Comment by jeremytrimble** [comment]
Farzad,

Just wondering whether that worked for you.  I also just sent xilinx a pull request with some other (alleged) improvements I made to the AXI DMA driver.  If you were still having trouble, you may want to try these out: https://github.com/Xilinx/linux-xlnx/pull/76

-Jeremy

**Comment by farzad64** [comment]
Hi Jeremy,

Sorry, I did not try it. I modified my AXI-stream hardware to generate smaller frames.

Farzad

**Comment by jeremytrimble** [comment]
Oh, ok.  Is that working well for you?  I'm just curious about how ezdma is getting used.

Feel free to close this issue (can always re-open another if you run into other problems).

**Comment by farzad64** [comment]
One annoying thing is when I call the read function with number of bytes less than number of bytes in AXI-stream frame, the function does not return and hangs. Again, I am sure if it is an ezdma issue. AFAIK the AXI DMA waits for the tlast signal to generate an interrupt and I believe I also had this issue with bare metal application.

**Comment by jeremytrimble** [comment]
Farzad,

Yes, the way ezdma and the AXI DMA driver are written currently, the size passed to read() must equal the size of the AXI Stream packet (which thus must be known in advance).  Unfortunately it's not easy to recognize when less than the expected amount of data has arrived (how would the AXI DMA "know" that more data wasn't coming?).

Perhaps ezdma could be modified to make use of the new "residue querying" functionality in the dmaengine API (if the AXI DMA driver's residue support works -- I haven't tested it myself).  However, this would still probably only allow descriptor-level resolution on short reads.

**Comment by farzad64** [comment]
Jeremy,

Thanks for your response. I will close the issue.
