### ISSUE TITLE
Physical Addresses

### ISSUE THREAD

**Issue by asagot** [jeremytrimble/ezdma#4]
Hi Jeremy,

I don't have an issue but three questions about your code which I am looking at for educational purposes.
1. 
   I want to report the physical addresses of the pages so I entered the following right after the dmap_map_sg() function

`printk("Physical Address: 0x%08lX", sg_dma_address(table.sgl));`

The value reported makes sense but this seems to only get the address of the first page. Any idea how I can print out the physical address for each of the pages in the scatterlist?

2.I am having a hard time understanding the following piece of code

`//sg_set_page( sgl, p_info->inflight.pinned_pages[i], len, offset );`
`sg_set_page( sg, p_info->inflight.pinned_pages[i], len, offset );`
 `left_to_map -= len;
`

my main confusion comes from the fact that sg is not used again in the function, can you explain how this works?
1. If I wanted to adapt your driver for the CDMA core, would the flow work the same except that I would set up two scatterlists? one for the source bufferand one for the destination buffer

**Comment by jeremytrimble** [comment]
@asagot:

The scatterlist data structure in Linux stores a series of addresses and lengths and has a special provision for "chaining" multiple entries.  See here: https://lwn.net/Articles/256368/.  You're correct that the kernel (often) returns a chain of mappings corresponding to each entry in the original scatterlist (though sometimes it is able to condense these mappings into fewer if the elements of the original list are contiguous or the system has an IOMMU).  You should be able to loop over the resulting scatterlist using the for_each_sg() macro (from scatterlist.h) and print all the physical addresses using sg_dma_address() like you have above.
1. The "sg" field used in the for_each_sg() loop is actually just a temporary pointer that gets set to each subsequent element in the scatterlist upon each subsequent iteration of the loop.  Again, have a look at for_each_sg() in scatterlist.h for background.  Also see sg_alloc_table().
2. For the CDMA core, I think that is one way you could do it, though one of the main points of ezdma is to offer a simple read()/write() interface like what is typically used for file I/O.  This works fine in the case of "slave DMA" (e.g. like the AXI DMA where data is transferred to the AXI Stream bus to/from main memory), but doesn't map as easily to the "CDMA" case where there is addressable memory on both sides of the DMA transaction (you might need to introduce a custom ioctl() interface to provide the destination addresses for write() calls or the source address for read() calls).  Just a thought.  Also, you'll need to use dmaengine's "memcpy" API rather than "slave".

**Comment by asagot** [comment]
Thank you so much for the feedback. I think I have enough to move forward.
